set_config("toolchain", "clang")

add_repositories("private-repo private_repo")
add_requires("doctest")
add_requires("mem_comparable_closure")

target("test")
   set_kind("binary")
   add_files("src/*.cpp")
   add_files("test/*.cpp")
   add_packages("mem_comparable_closure")
   add_packages("doctest")
   set_languages("cxx17")
   add_includedirs("include")
   set_optimize("debug")
   set_warnings("allextra")
   
-- Proof of concept1
target("poc1")
   set_kind("binary")
   add_files("src/*.cpp")
   add_files("poc1/*.cpp")
   add_packages("mem_comparable_closure")
   set_languages("cxx17")
   add_includedirs("include")
   set_optimize("debug")
   set_symbols("debug")
   set_warnings("allextra")
