set_config("toolchain", "clang")

add_repositories("private-repo private_repo")
add_requires("boost")
add_requires("doctest")
add_requires("xcb")
add_requires("harfbuzz")
add_requires("freetype2")
add_requires("xcb-render")
add_requires("xcb-image")
add_requires("mem_comparable_closure")

target("test")
   set_kind("binary")
   add_files("src/*.cpp")
   add_files("test/*.cpp")
   add_packages("mem_comparable_closure")
   add_packages("boost")
   add_packages("xcb")
   add_packages("doctest")
   add_packages("harfbuzz")
   add_packages("freetype2")
   add_packages("xcb-render")
   add_packages("xcb-image")
   set_languages("cxx17")
   add_includedirs("include")
   add_includedirs("src/include")
   set_optimize("debug")
   set_symbols("debug")
   set_warnings("allextra")
   
-- Proof of concept1
target("poc1")
   set_kind("binary")
   add_files("src/*.cpp")
   add_files("poc1/*.cpp")
   add_packages("mem_comparable_closure")
   add_packages("boost")
   add_packages("xcb")
   add_packages("harfbuzz")
   add_packages("freetype2")
   add_packages("xcb-render")
   add_packages("xcb-image")
   set_languages("cxx17")
   add_includedirs("include")
   add_includedirs("src/include")
   set_optimize("debug")
   set_symbols("debug")
   set_warnings("allextra")
