package("mem_comparable_closure")
    set_description("for closures that can be compared")
    set_urls("https://github.com/Glinrens-corner/mem_comparable_closure.git")
    add_versions("0.0.6", "578427a24a42041071e251eab10cb35056faa80b")
    on_install(function(package)
        os.cp("mem_comparable_closure/include/*", package:installdir("include"))
    end)
